insert into members (member_id, full_name, sports, gender, member_type) values
('aaron_finch', 'Aaron Finch', 'Cricket', 'M', 'athlete'),
('adam_zampa', 'Adam Zampa', 'Cricket', 'M', 'athlete'),
('adil_rashid', 'Adil Rashid', 'Cricket', 'M', 'athlete'),
('alex_carey', 'Alex Carey', 'Cricket', 'M', 'athlete'),
('andre_russell', 'Andre Russell', 'Cricket', 'M', 'athlete'),
('angelo_mathews', 'Angelo Mathews', 'Cricket', 'M', 'athlete'),
('anrich_nortje', 'Anrich Nortje', 'Cricket', 'M', 'athlete'),
('avishka_fernando', 'Avishka Fernando', 'Cricket', 'M', 'athlete'),
('babar_azam', 'Babar Azam', 'Cricket', 'M', 'athlete'),
('ben_stokes', 'Ben Stokes', 'Cricket', 'M', 'athlete'),
('bhuvneshwar_kumar', 'Bhuvneshwar Kumar', 'Cricket', 'M', 'athlete'),
('chris_morris', 'Chris Morris', 'Cricket', 'M', 'athlete'),
('dale_steyn', 'Dale Steyn', 'Cricket', 'M', 'athlete'),
('david_warner', 'David Warner', 'Cricket', 'M', 'athlete'),
('dinesh_karthik', 'Dinesh Karthik', 'Cricket', 'M', 'athlete'),
('eoin_morgan', 'Eoin Morgan', 'Cricket', 'M', 'athlete'),
('faf_du_plessis', 'Faf du Plessis', 'Cricket', 'M', 'athlete'),
('fakhar_zaman', 'Fakhar Zaman', 'Cricket', 'M', 'athlete'),
('gulbadin_naib', 'Gulbadin Naib', 'Cricket', 'M', 'athlete'),
('hardik_pandya', 'Hardik Pandya', 'Cricket', 'M', 'athlete'),
('imam-ul-haq', 'Imam-ul-Haq', 'Cricket', 'M', 'athlete'),
('isuru_udana', 'Isuru Udana', 'Cricket', 'M', 'athlete'),
('jason_behrendorff', 'Jason Behrendorff', 'Cricket', 'M', 'athlete'),
('jason_holder', 'Jason Holder', 'Cricket', 'M', 'athlete'),
('jason_roy', 'Jason Roy', 'Cricket', 'M', 'athlete'),
('jasprit_bumrah', 'Jasprit Bumrah', 'Cricket', 'M', 'athlete'),
('jeevan_mendis', 'Jeevan Mendis', 'Cricket', 'M', 'athlete'),
('joe_root', 'Joe Root', 'Cricket', 'M', 'athlete'),
('jonny_bairstow', 'Jonny Bairstow', 'Cricket', 'M', 'athlete'),
('jos_buttler', 'Jos Buttler', 'Cricket', 'M', 'athlete'),
('jp_duminy', 'JP Duminy', 'Cricket', 'M', 'athlete'),
('k._l._rahul', 'KL Rahul', 'Cricket', 'M', 'athlete'),
('kane_williamson', 'Kane Williamson', 'Cricket', 'M', 'athlete'),
('kemar_roach', 'Kemar Roach', 'Cricket', 'M', 'athlete'),
('kuldeep_yadav', 'Kuldeep Yadav', 'Cricket', 'M', 'athlete'),
('kusal_perera', 'Kusal Perera', 'Cricket', 'M', 'athlete'),
('lasith_malinga', 'Lasith Malinga', 'Cricket', 'M', 'athlete'),
('lungi_ngidi', 'Lungi Ngidi', 'Cricket', 'M', 'athlete'),
('marcus_stoinis', 'Marcus Stoinis', 'Cricket', 'M', 'athlete'),
('mitchell_starc', 'Mitchell Starc', 'Cricket', 'M', 'athlete'),
('moeen_ali', 'Moeen Ali', 'Cricket', 'M', 'athlete'),
('mohammad_hafeez', 'Mohammad Hafeez', 'Cricket', 'M', 'athlete'),
('ms_dhoni', 'MS Dhoni', 'Cricket', 'M', 'athlete'),
('mujeeb_ur_rahman', 'Mujeeb Ur Rahman', 'Cricket', 'M', 'athlete'),
('mushfiqur_rahim', 'Mushfiqur Rahim', 'Cricket', 'M', 'athlete'),
('nathan_coulter_nile', 'Nathan Coulter-Nile', 'Cricket', 'M', 'athlete'),
('nicholas_pooran', 'Nicholas Pooran', 'Cricket', 'M', 'athlete'),
('pat_cummins', 'Pat Cummins', 'Cricket', 'M', 'athlete'),
('quinton_de_kock', 'Quinton de Kock', 'Cricket', 'M', 'athlete'),
('rashid_khan', 'Rashid Khan', 'Cricket', 'M', 'athlete'),
('ravindra_jadeja', 'Ravindra Jadeja', 'Cricket', 'M', 'athlete'),
('rohit_sharma', 'Rohit Sharma', 'Cricket', 'M', 'athlete'),
('ross_taylor', 'Ross Taylor', 'Cricket', 'M', 'athlete'),
('samiullah_shinwari', 'Samiullah Shinwari', 'Cricket', 'M', 'athlete'),
('sarfaraz_ahmed', 'Sarfaraz Ahmed', 'Cricket', 'M', 'athlete'),
('shadab_khan', 'Shadab Khan', 'Cricket', 'M', 'athlete'),
('shakib_al_hasan', 'Shakib Al Hasan', 'Cricket', 'M', 'athlete'),
('shikhar_dhawan', 'Shikhar Dhawan', 'Cricket', 'M', 'athlete'),
('shimron_hetmyer', 'Shimron Hetmyer', 'Cricket', 'M', 'athlete'),
('shoaib_malik', 'Shoaib Malik', 'Cricket', 'M', 'athlete'),
('steve_smith', 'Steve Smith', 'Cricket', 'M', 'athlete'),
('tabraiz_shamsi', 'Tabraiz Shamsi', 'Cricket', 'M', 'athlete'),
('thisara_perera', 'Thisara Perera', 'Cricket', 'M', 'athlete'),
('tom_curran', 'Tom Curran', 'Cricket', 'M', 'athlete'),
('trent_boult', 'Trent Boult', 'Cricket', 'M', 'athlete'),
('vijay_shankar', 'Vijay Shankar', 'Cricket', 'M', 'athlete'),
('virat_kohli', 'Virat Kohli', 'Cricket', 'M', 'athlete');
